
//Foursquare API
var API_FOURSQUARE_URL = 'https://api.foursquare.com/v2';
var API_FOURSQUARE_CLIENT_ID = 'OO5NWCVYRSZVNDXUDUDSJVWRPNXPEOEJRUGOJZGVEHQMTISJ';
var API_FOURSQUARE_CLIENT_SECRET = 'ZCFXECDNZJZPEFN3FSBCJKJCCJGPVWBSCRUTZL41F3NIWRLE';
